# we plan to cache the rust compiler to shorten build times
language: minimal

env:
  global:
  - RUST_BACKTRACE=1

cache:
  directories:
  # cache rust compiler
  - "$HOME/.rustup"
  # cache cargo, for cargo subcommands
  - "$HOME/.cargo"
  # cache kcov, we don't want to recompile it every time, only used in nightly
  - target/kcov-master/build

before_cache:
# we dont want to cache crates
- rm -rf "$HOME/.cargo/registry"

before_install:
- curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
- source $HOME/.cargo/env
- rustup update

before_script:
- cargo build
- cargo test
- if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    cargo doc;
  else
    cargo rustdoc -- -Z unstable-options --enable-index-page;
    cargo bench;
  fi

jobs:
  include:
  - os: linux
    env:
    - TRAVIS_RUST_VERSION=nightly
    sudo: required
    addons:
      apt:
        packages:
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
        - binutils-dev
        - cmake
    script:
    # install and update cargo subcommands
    # check cargo-travis for updates
    # upload test coverage
    # decrypt deploy key
    # start ssh agent in background
    # add deploy key to ssh
    # upload the documentation
    - if [ "$TRAVIS_PULL_REQUEST" == false ]; then
        cargo install cargo-update || echo "cargo-update already installed";
        cargo install cargo-travis --git "https://github.com/daxpedda/cargo-travis.git" || echo "cargo-travis already installed";
        cargo install-update -a -g;
        cargo coverage;
        bash <(curl -s https://codecov.io/bash) -s target/kcov;
        openssl aes-256-cbc -K $encrypted_ea461eafb522_key -iv $encrypted_ea461eafb522_iv -in ".travis/github_deploy_key.enc" -out ".travis/github_deploy_key" -d;
        chmod 600 ".travis/github_deploy_key";
        eval "$(ssh-agent -s)";
        ssh-add ".travis/github_deploy_key";
        cargo doc-upload --branch $TRAVIS_BRANCH;
      fi

  - os: linux
    env:
    - TRAVIS_RUST_VERSION=beta

  - os: linux
    env:
    - TRAVIS_RUST_VERSION=stable

  - os: osx
    env:
    - TRAVIS_RUST_VERSION=nightly

  - os: windows
    language: node_js
    node_js: "7"
    env:
    - TRAVIS_RUST_VERSION=nightly
