# don't run build unless we are on the specified branches
branches:
  only:
  - master
  - release

language: rust

env:
  global:
  - RUST_BACKTRACE=1

cache:
  directories:
  # cache cargo, for cargo subcommands
  - $HOME/.cargo

before_cache:
# we don't want to cache crates
- rm -rf "$HOME/.cargo/registry"

script:
- .travis/script.sh

jobs:
  include:
  - os: linux
    rust: nightly-2018-12-23
    env:
    - DEPLOY: true
    # we want to save secure variables inside the file instead of the website because windows doesn't work if there are secure variables set
    - secure: dquCvtj47KvkKO8PlZBGvVD8S97CwO4ExpzKaAbyiIOgeIK9Q6N8pCYYGXxJNTyYpqlckRt9OeQNjba0HporcrpGw/iz8pEZ25t1A/Uh4CdysKf3WKx9GWepnoTruFvylNesljf15Tp8/Bzq2bSP4c2k80QCT40cQwtLSAAwlXXPMqsvqIA0NJdOEbmpLtbwoI2lr8fBl8JzZ9S4wJdJXuizPJL0jZhKX+mVwoqMb1x3lKwMUsoEU+VwU1iFhicHOWVXn4n4fCIRmOb1uD0aD4uW0x67INCnKULcizYd2xM0gmZm7smofdZ+xKbNMQqzbTlQNmJ1ZRv8jY/aWD9rKCvKmKE4p18gDzhBDkPZ83u9YWga9r9+Bbw+7FlIiqVgYLpatIIKnnuWP/eO8z3edgDo5IyNdOEs07NCiV2u8pNN/G1/lOxBa7ak3ADcd/guVS+L2JuDkBjjzteKUYBG8x5jl13WM6jHTnuxCTh7bpmij3CZlBfKHC8m/sCyv4WRLbsIRWM7w4AmQTVvZ/I1mswdpyPNme9JRqAncSIQHiRqeb5O5t1xOGGCIOdw1nErKbEHz+XRHZmCHDesKF+pKBvsF2a+F6RPktkAyvucDq1PaJs5hn+98up7IhR6X8krqjmEtD/zR0q08gc83+xrY+ODJMT+iSq7ZTtI/ph93pQ=

  - os: linux
    rust: beta

  - os: linux
    rust: stable
