language: minimal # we plan to cache the rust compiler to shorten build times

env:
  global:
  - RUST_BACKTRACE=1

cache:
  directories:
  - "$HOME/.rustup" # cache rust compiler
  - "$HOME/.cargo" # cache cargo, for cargo subcommands
  - target/kcov-master/build # cache kcov, we don't want to recompile it every time, only used in nightly

before_cache:
- rm -rf "$HOME/.cargo/registry" # we dont want to cache crates

before_install:
- curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
- source $HOME/.cargo/env
- rustup update

before_script:
- cargo build
- cargo test
- if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    cargo doc;
  else
    cargo rustdoc -- -Z unstable-options --enable-index-page;
  fi

jobs:
  include:
  - os: linux
    env:
    - TRAVIS_RUST_VERSION=nightly
    sudo: required
    addons:
      apt:
        packages:
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
        - binutils-dev
        - cmake
    script:
    - cargo bench
    - if [ "$TRAVIS_PULL_REQUEST" == false ]; then
        cargo install cargo-update || echo "cargo-update already installed";
        cargo install cargo-travis || echo "cargo-travis already installed";
        cargo install-update -a;
        cargo coverage;
        bash <(curl -s https://codecov.io/bash) -s target/kcov; # upload test coverage
        openssl aes-256-cbc -K $encrypted_ea461eafb522_key -iv $encrypted_ea461eafb522_iv -in ".travis/github_deploy_key.enc" -out ".travis/github_deploy_key" -d; # dencrypt deploy key
        chmod 600 ".travis/github_deploy_key";
        eval "$(ssh-agent -s)";
        ssh-add ".travis/github_deploy_key"; # add deploy key to ssh
        cargo doc-upload --branch $TRAVIS_BRANCH; # upload the documentation
      fi

  - os: linux
    env:
    - TRAVIS_RUST_VERSION=beta

  - os: linux
    env:
    - TRAVIS_RUST_VERSION=stable
