# don't run build unless we are on the specified branches
branches:
  only:
  - master
  - release

language: rust

env:
  global:
  - RUST_BACKTRACE=1

cache:
  directories:
  # cache cargo, for cargo subcommands
  - $HOME/.cargo

before_cache:
# we don't want to cache crates
- rm -rf "$HOME/.cargo/registry"

script:
- bash .travis/script.sh

jobs:
  include:
  - os: linux
    rust: nightly-2018-12-23
    env:
    - DEPLOY: true

  - os: linux
    rust: beta

  - os: linux
    rust: stable
