language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

cache:
  cargo: true
  directories:
    - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then target/kcov-master/build; fi

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo build
  - cargo test
  - cargo doc
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo bench; fi

matrix:
  include:
    - os: linux
      rust: nightly
      sudo: required
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - cmake
      script:
        - cargo build
        - cargo test
        - cargo doc
        - cargo bench
        - cargo install cargo-update
        - cargo install cargo-travis
        - cargo install-update -a
        - cargo coverage
        - bash <(curl -s https://codecov.io/bash) -s target/kcov
        - cargo doc-upload
  exclude:
    - os: linux
      rust: nightly
