language: rust

rust:
  - stable
  - beta

os:
  - linux
  - osx
  - windows

cache:
  cargo: true
  directories:
    - target/kcov-master/build

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo build
  - cargo test
  - cargo doc

matrix:
  include:
    - os: linux
      rust: nightly
      sudo: required
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - cmake
      script:
        - cargo build
        - cargo test
        - cargo doc
        - cargo bench
        - cargo install cargo-update || echo "cargo-update already installed"
        - cargo install cargo-travis || echo "cargo-travis already installed"
        - cargo install-update -a
        - cargo coverage
        - bash <(curl -s https://codecov.io/bash) -s target/kcov
        - cargo doc-upload
    - os: osx
      rust: nightly
      after_sucess:
        - cargo bench
    - os: windows
      rust: nightly
      after_sucess:
        - cargo bench
