branches:
  only:
  - master
  - stable

# we plan to cache the rust compiler to shorten build times
language: minimal

env:
  global:
  - RUST_BACKTRACE=1

cache:
  directories:
  # cache rust compiler
  - "$HOME/.rustup"
  # cache cargo, for cargo subcommands
  - "$HOME/.cargo"
  # cache kcov, we don't want to recompile it every time, only used in nightly
  - target/kcov-master/build

before_cache:
# we don't want to cache crates
- rm -rf "$HOME/.cargo/registry"

before_install:
# download the rust installer
- curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
# different command needed for windows
- if [ "$TRAVIS_OS_NAME" != "windows" ]; then
    source $HOME/.cargo/env;
  else
    export PATH=$HOME/.cargo/bin:$PATH;
  fi
# FIXME: find out if the installer is enough to update
# FIXME: if installer already updates, we should only download the installer if rust isn't installed
- rustup update

before_script:
- cargo build
- cargo test
# nightly has additional features we want to test and use
- if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    cargo doc;
  else
    cargo rustdoc -- -Z unstable-options --enable-index-page;
    cargo bench;
  fi

jobs:
  include:
  - os: linux
    env:
    - TRAVIS_RUST_VERSION=nightly
    - secure: w+WO9q3FHudm6NrVBbSh2zsU7DLS7SG9aTVzzNzXkz+9OG3wmWp70iM98qbbb1UEfjTjiR7BiCcqj9lyqtHz+yZS2fh/zvAruY41AYxkYrZT9EtWFCdL3kOxyc6x2kiW3qwtpa581rjN8Y3j1WH41yJKg1ZDEBor5Oh3oABMxILwo3d6Ol35F2LE5OTJJZ/16EPEJAPIYKaZJ6OLwysla/dNrGNtzbDwHCdsju2bHCHFX84KU76hG1WQSSfMh2DN++NtHwtQ7KrXts6t1PHdiDuucT4wOf0ZDecqkU9CMRh9rrF04uouBPVcZfZznNMiLM0yQc1z6M1fhZxU/oh0sqlN7N1lonSOlDBud5eDR+VhGHHUNLDLLmJhYYXOTthDZPbAWNOQyLCOjyaom1FoiYinNzDCrNv16rTDwJakIiFkyswSUztPIlrtKWDgbD3DOkh6OGO/tvaHeeJlqWKXUYKCUrcR0ruQqW20Hc56ZP+qm5J1PfWMMNGunOd6heIad1Oc5Uw7/Ml4AnUp+kxHyaFkjtAa7uokK+PuvtztjgBy+tw91p5I/sdKhYVIRaYa+bbB33eHo6xjHYLvNFlIMouhNtB3kUL7imiKY2CXA3Wtd3/R6OnR2PhK5CIy6/WXrwvjl/mGRDFnUM9axOAcRKN9SWmc2103mrd0TE6y0Gg=
    sudo: required
    addons:
      apt:
        packages:
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
        - binutils-dev
        - cmake
    script:
    # install and update cargo subcommands
    # run coverage
    # upload test coverage
    # decrypt deploy key
    # start ssh agent in background
    # add deploy key to ssh
    # upload the documentation
    - if [ "${TRAVIS_PULL_REQUEST}" == false ]; then
        cargo install cargo-update || echo "cargo-update already installed";
        cargo install cargo-travis --git "https://github.com/daxpedda/cargo-travis.git" || echo "cargo-travis already installed";
        cargo install-update -a -g;
        cargo coverage;
        bash <(curl -s https://codecov.io/bash) -s target/kcov;
        echo $github_deploy_key | gpg --passphrase-fd 0 ".travis/github_deploy_key.gpg"
        chmod 600 ".travis/github_deploy_key";
        eval "$(ssh-agent -s)";
        ssh-add ".travis/github_deploy_key";
        cargo doc-upload --branch $TRAVIS_BRANCH;
      fi

  - os: linux
    env:
    - TRAVIS_RUST_VERSION=beta

  - os: linux
    env:
    - TRAVIS_RUST_VERSION=stable

  - os: osx
    env:
    - TRAVIS_RUST_VERSION=nightly

  - os: windows
    language: sh
    env:
    - RUST_BACKTRACE=1
    - TRAVIS_RUST_VERSION=nightly
    cache:
      directories:
      # cache rust compiler
      - "$HOME/.rustup"
      # cache cargo, for cargo subcommands
      - "$HOME/.cargo"
      # cache kcov, we don't want to recompile it every time, only used in nightly
      - target/kcov-master/build
    before_cache:
    # we dont want to cache crates
    - rm -rf "$HOME/.cargo/registry"
    before_install:
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
    - export PATH=$HOME/.cargo/bin:$PATH
    - rustup update
    before_script:
    - cargo build
    - cargo test
    - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
        cargo doc;
      else
        cargo rustdoc -- -Z unstable-options --enable-index-page;
        cargo bench;
      fi
