# don't run build unless we are on the specified branches
branches:
  only:
  - master
  - release

language: rust

rust:
- stable
- beta
- nightly

env:
  global:
  - RUST_BACKTRACE=1

cache:
  directories:
  # cache cargo, for cargo subcommands
  - $HOME/.cargo

before_cache:
# we don't want to cache crates
- rm -rf "$HOME/.cargo/registry"

script:
- bash .travis/build.sh

notifications:
  email:
    recipients:
    - secure: "eq1pCEarZ3FlRWvOEUucS6iGw2v5wVreBLAyoiAZGvvQo1lZ/IUvQ9uWQ5yz+DE5+uD1v2TLZYbDjL/9JITFhofvQ9lN03WMXZO2IMuSzDGH0y63XjHPPWA1NxtcxnWsdF2hHK/+O2Mmc9xTnsVNHv+DA3JFg0ZgKcLgdxxIuZWG+ZSrDvqD5W6Bthdshp0DzVYwN+c+ikoF94BPNs76nVRamBDdHA/JCEMNbZYGQOebpUSWB0dpt3hj7z3svBdW4bILM8Q34fBTPqhdB8Otu0Rj5mjlNJC9LmBuZal7QIB93bznULnA0Jb0wwxu+6R4usjzC+2gbAn3hWU3sUMN4oTsHv4qvG7wUmrg8mumhGr89KPdDgPTdp2JetwXxK02j37oHKMBdTqAJJfmlfqyMv3r7He6a4KFywdvRUSedVSENlQDLDAU0Vc2J8EqfuXtEmzUCZPOxG6r9tdren7ey3zAHipXjcv4DDiHWertZ/or31zK1S4zzRPK09PWQ4cCnwtsQ5mFhmpi7DB/y4984zv5TBLeTZthH2oZO6QbylTJew4TWqyIwxpCxXsfGKjCjEMCWVrnfLmOEvL4vfpIveN6kl3PafVshHrIMKFaO/rnMHMnrLGzvUhjlOaVhl36EQYhyvhaDj6iaUaC4our22HbAiUFKkHXZluAvbXMEMY="
    on_success: never
    on_failure: always
