# don't run build unless we are on the specified branches
branches:
  only:
  - master
  - stable

language: rust

env:
  global:
  - RUST_BACKTRACE=1

cache:
  directories:
  # cache cargo, for cargo subcommands
  - $HOME/.cargo

before_cache:
# we don't want to cache crates
- rm -rf "$HOME/.cargo/registry"

before_script:
- rustup component add clippy
- rustup component add rustfmt
- cargo build
- cargo build --release
- cargo test
- cargo test --release
- cargo clippy --all-features -- -D warnings
- cargo clippy --all-features --tests -- -D warnings
- cargo fmt --all -- --check
# nightly has additional features we want to test and use
- if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    cargo doc;
  else
    cargo clippy --all-features --benches -- -D warnings
    cargo rustdoc -- -Z unstable-options --enable-index-page;
    cargo bench;
  fi

jobs:
  include:
  - os: linux
    rust: nightly
    env:
    # we want to save secure variables inside the file instead of the website because windows doesn't work if there are secure variables set
    - secure: dquCvtj47KvkKO8PlZBGvVD8S97CwO4ExpzKaAbyiIOgeIK9Q6N8pCYYGXxJNTyYpqlckRt9OeQNjba0HporcrpGw/iz8pEZ25t1A/Uh4CdysKf3WKx9GWepnoTruFvylNesljf15Tp8/Bzq2bSP4c2k80QCT40cQwtLSAAwlXXPMqsvqIA0NJdOEbmpLtbwoI2lr8fBl8JzZ9S4wJdJXuizPJL0jZhKX+mVwoqMb1x3lKwMUsoEU+VwU1iFhicHOWVXn4n4fCIRmOb1uD0aD4uW0x67INCnKULcizYd2xM0gmZm7smofdZ+xKbNMQqzbTlQNmJ1ZRv8jY/aWD9rKCvKmKE4p18gDzhBDkPZ83u9YWga9r9+Bbw+7FlIiqVgYLpatIIKnnuWP/eO8z3edgDo5IyNdOEs07NCiV2u8pNN/G1/lOxBa7ak3ADcd/guVS+L2JuDkBjjzteKUYBG8x5jl13WM6jHTnuxCTh7bpmij3CZlBfKHC8m/sCyv4WRLbsIRWM7w4AmQTVvZ/I1mswdpyPNme9JRqAncSIQHiRqeb5O5t1xOGGCIOdw1nErKbEHz+XRHZmCHDesKF+pKBvsF2a+F6RPktkAyvucDq1PaJs5hn+98up7IhR6X8krqjmEtD/zR0q08gc83+xrY+ODJMT+iSq7ZTtI/ph93pQ=
    script:
    # install and update cargo subcommands
    # run coverage
    # upload test coverage
    # decrypt deploy key
    # start ssh agent in background
    # add deploy key to ssh
    # upload the documentation
    - if [ "${TRAVIS_PULL_REQUEST}" == false ]; then
        cargo install cargo-update || echo "cargo-update already installed";
        RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --git "https://github.com/daxpedda/tarpaulin.git" --branch "develop" || echo "cargo-tarpaulin already installed";
        cargo install cargo-travis --git "https://github.com/daxpedda/cargo-travis.git" || echo "cargo-travis already installed";
        cargo install-update install-update;
        RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install-update cargo-tarpaulin -g;
        cargo install-update cargo-travis -g;
        cargo tarpaulin --skip-clean --out Xml;
        bash <(curl -s https://codecov.io/bash);
        cargo tarpaulin --skip-clean --release --out Xml;
        bash <(curl -s https://codecov.io/bash);
        echo $github_deploy_key | gpg --passphrase-fd 0 ".travis/github_deploy_key.gpg";
        chmod 600 ".travis/github_deploy_key";
        eval "$(ssh-agent -s)";
        ssh-add ".travis/github_deploy_key";
        cargo doc-upload --branch $TRAVIS_BRANCH;
      fi

  - os: linux
    rust: beta

  - os: linux
    rust: stable

  - os: osx
    rust: nightly

  - os: windows
    rust: nightly
