[package]
name = "unchecked_unwrap"
version = "0.9.1"
authors = ["daxpedda <daxpedda@users.noreply.github.com>"]
edition = "2018"
description = "Adds an unchecked version of `unwrap()` and `expect()` to Option and Result."
documentation = "https://docs.rs/crate/unchecked_unwrap/"
homepage = "https://github.com/daxpedda/unchecked_unwrap/"
repository = "https://github.com/daxpedda/unchecked_unwrap/tree/stable/"
readme = "README.MD"
keywords = ["unwrap", "unchecked", "expect", "result", "option"]
categories = ["no-std", "rust-patterns"]
license = "MIT OR Apache-2.0"
exclude = [".travis.yml", "codecov.yml"]

[badges]
travis-ci = { repository = "daxpedda/unchecked_unwrap", branch = "stable" }
# TODO: wait for tarpaulin to fix some issues regarding uncovered lines
# codecov = { repository = "daxpedda/unchecked_unwrap", branch = "stable" }
is-it-maintained-issue-resolution = { repository = "daxpedda/unchecked_unwrap" }
is-it-maintained-open-issues = { repository = "daxpedda/unchecked_unwrap" }
maintenance = { status = "actively-developed" }

[features]
default = ["debug_checks"]
debug_checks = []

[lib]
test = false
bench = false
