name: CI

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages
  schedule:
    - cron: "0 0 * * *"

jobs:
  cargo-audit:
    if: github.event_name != 'schedule'

    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
      - name: Cache
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.cargo-cache
          key: cargo-audit
      - name: Unpack Cache
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          mv ~/.cargo-cache/.crates.toml ~/.cargo
          mv ~/.cargo-cache/.crates2.json ~/.cargo
          mv ~/.cargo-cache/bin/cargo-audit ~/.cargo/bin
          rm -r ~/.cargo-cache/
      - name: Install cargo-audit
        id: install
        run: cargo -v install cargo-audit
      - name: Checkout
        uses: actions/checkout@v2
      - name: Audit
        run: cargo audit -D
      - name: Package Cache
        run: |
          mkdir ~/.cargo-cache
          mv ~/.cargo/.crates.toml ~/.cargo-cache
          mv ~/.cargo/.crates2.json ~/.cargo-cache
          mkdir ~/.cargo-cache/bin
          mv ~/.cargo/bin/cargo-audit ~/.cargo-cache/bin

  prettier:
    if: github.event_name != 'schedule'

    runs-on: ubuntu-latest

    steps:
      - name: Install Prettier
        run: npm install --no-save prettier prettier-plugin-toml
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prettier
        run: npx prettier -l .

  ci:
    if: github.event_name != 'schedule'

    strategy:
      fail-fast: false
      matrix:
        rust:
          - { channel: stable, continue-on-error: false }
          - { channel: beta, continue-on-error: false }
          - { channel: nightly, continue-on-error: true }
        feature:
          - --no-default-features
          - ""
          - --no-default-features --features nightly
          - --features nightly
        profile:
          - ""
          - --release
        exclude:
          - rust: { channel: stable, continue-on-error: false }
            feature: --no-default-features --features nightly
          - rust: { channel: stable, continue-on-error: false }
            feature: --features nightly
          - rust: { channel: beta, continue-on-error: false }
            feature: --no-default-features --features nightly
          - rust: { channel: beta, continue-on-error: false }
            feature: --features nightly

    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust.channel }}
          components: rustfmt, clippy
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Build
        id: build
        run: cargo -v build ${{ matrix.feature }} ${{ matrix.profile }}
      - name: Clippy
        if: always() && steps.checkout.outcome == 'success'
        run: cargo clippy -v --all-targets ${{ matrix.feature }} ${{ matrix.profile }} -- -D warnings
      - name: Test
        if: always() && steps.build.outcome == 'success'
        run: cargo -v test ${{ matrix.feature }} ${{ matrix.profile }}
      - name: Bench
        if: always() && steps.build.outcome == 'success' && matrix.rust.channel == 'nightly' && matrix.profile == '--release'
        run: cargo -v bench ${{ matrix.feature }}
      - name: Documentation
        if: always() && steps.checkout.outcome == 'success'
        run: cargo -v doc --no-deps --document-private-items ${{ matrix.feature }} ${{ matrix.profile }}
      - name: Rust Formatting
        if: always() && steps.checkout.outcome == 'success'
        continue-on-error: ${{ matrix.rust.continue-on-error }}
        run: cargo fmt -v --all -- --check

  schedule-cargo-audit:
    if: github.event_name == 'schedule'

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - release

    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
      - name: Install cargo-audit
        id: install
        run: cargo -v install cargo-audit
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Audit
        run: cargo audit -D

  schedule-prettier:
    if: github.event_name == 'schedule'

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - release

    runs-on: ubuntu-latest

    steps:
      - name: Install Prettier
        run: npm install --no-save prettier prettier-plugin-toml
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Prettier
        run: npx prettier -l .

  schedule-ci:
    if: github.event_name == 'schedule'

    strategy:
      fail-fast: false
      matrix:
        rust:
          - { channel: stable, continue-on-error: false }
          - { channel: beta, continue-on-error: false }
          - { channel: nightly, continue-on-error: true }
        feature:
          - --no-default-features
          - ""
        profile:
          - ""
          - --release
        branch:
          - master
          - release
        exclude:
          - rust: { channel: stable, continue-on-error: false }
            feature: --no-default-features --features nightly
          - rust: { channel: stable, continue-on-error: false }
            feature: --features nightly
          - rust: { channel: beta, continue-on-error: false }
            feature: --no-default-features --features nightly
          - rust: { channel: beta, continue-on-error: false }
            feature: --features nightly

    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust.channel }}
          components: rustfmt, clippy
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Build
        id: build
        run: cargo -v build ${{ matrix.feature }} ${{ matrix.profile }}
      - name: Clippy
        if: always() && steps.checkout.outcome == 'success'
        run: cargo clippy -v --all-targets ${{ matrix.feature }} ${{ matrix.profile }} -- -D warnings
      - name: Test
        if: always() && steps.build.outcome == 'success'
        run: cargo -v test ${{ matrix.feature }} ${{ matrix.profile }}
      - name: Bench
        if: always() && steps.build.outcome == 'success' && matrix.rust.channel == 'nightly' && matrix.profile == '--release'
        run: cargo -v bench ${{ matrix.feature }}
      - name: Documentation
        if: always() && steps.checkout.outcome == 'success'
        run: cargo -v doc --no-deps --document-private-items ${{ matrix.feature }} ${{ matrix.profile }}
      - name: Rust Formatting
        if: always() && steps.checkout.outcome == 'success'
        continue-on-error: ${{ matrix.rust.continue-on-error }}
        run: cargo fmt -v --all -- --check
