name: docs

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Documentation
        env:
          RUSTDOCFLAGS: -Z unstable-options --enable-index-page
        run: cargo -v doc --features nightly --no-deps --document-private-items
      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc/
          TARGET_FOLDER: master/doc/
          CLEAN: true
