name: docs

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Checkout
        uses: actions/checkout@v3
      - name: Documentation
        env:
          RUSTDOCFLAGS: -Z unstable-options --enable-index-page
        run: cargo -v doc --all-features --no-deps
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc/
          GIT_CONFIG_NAME: github-actions
          GIT_CONFIG_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          TARGET_FOLDER: master/doc/
          CLEAN: true
